---
title: "Publications"
description: |
  Publications
  
output:
  distill::distill_article:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Working Papers

- Kasli, M., Zopluoglu, C., & Toton, S. (under review). A Deterministic Gated Lognormal Response Time Model to Identify Examinees with Item Preknowledge. <br>
[**Download Preprint**](https://psyarxiv.com/bqa3t)

- Dietz, S., Prilleltensky, I., McMahon, A., Zopluoglu, C., Lipsky, M., & Hartnett, C.(under review). Assessing a Culture of Belonging in a Higher Education Context.


- Zopluoglu, C., & Kasli, M. (in preparation). Simultaneous Detection of Compromised Items and Examinees with Item Preknowledge using Response Time Information.

- Zopluoglu, C. (in preparation). Simultaneous Detection of Compromised Items and Examinees with Item Preknowledge using Response Accuracy: Improvments on the Deterministic Gated Item Response Model.

- Zopluoglu, C., Combs, T. (in preparation). Modeling Response Times with Variable Latent Speed as a Piecewise Function.

- Zopluoglu, C. & colleagues (in preparation). GeoCAT: Designing a Computerized Adaptive Test to Measure Geometry Knowledge for K-3 Grades.

## Published Papers

- Scarpa, M.P., Zopluoglu, C., & Prilleltensky, I (in press). Mattering in the community. Domain and demographic differences in a US sample. Journal of Community Psychology.  https://doi.org/10.1002/jcop.22728 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- Scarpa, M.P., Zopluoglu, C., & Prilleltensky, I (in press). Assessing multidimensional mattering: Development and exploratory validation of the Mattering in Domains of Life Scale (MIDLS). Journal of Community Psychology. https://doi.org/10.1002/jcop.22725 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- Zopluoglu, C., Kasli, M., & Toton, S. (2021, in press). The Effect of Item Preknowledge on Response Time: Analysis of Two Datasets Using the Multiple-Group Lognormal Response Time Model with a Gating Mechanism. Educational Measurement: Issues and Practices, 40(3), 42-51. https://doi.org/10.1111/emip.12428 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- Patel, Z.S., Jensen-Doss, A. & Zopluoglu, C (2021, in press). Illustrating the Applicability of IRT to Implementation Science: Examining an Instrument of Therapist Attitudes. Administration and Policy in Mental Health Services Research, 48, 921-935. https://doi.org/10.1007/s10488-021-01139-1 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- Lee, J., Zopluoglu, C., Andersen, L., Stanton, A., Magidson, J., Kagee, A., Joska, J.A., O’Cleirigh, C., & Safren, S.A. (2021, in press). Improving the Measurement of Food Insecurity among People with HIV in South Africa: A Psychometric Examination. Public Health Nutrition, 24(12),3805-3817. https://doi:10.1017/S1368980021001312 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- Park, S.E., Ahn, S., & Zopluoglu, C. (2021). Differential item functioning effect size from the multigroup confirmatory factor analysis for a meta-analysis: A simulation study. Educational and Psychological Measurement, 81(1), 182-199. https://doi.org/10.1177/0013164420925885 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- de l’Etoile, S. K., Bennett, C., & Zopluoglu, C. (2020). Infant movement response to auditory rhythm. Perceptual and Motor Skills, 127(4), 651-670. 
https://doi.org/10.1177/0031512520922642 <br>
[**Download/Request**](mailto:cengiz@uoregon.edu)

- Prilleltensky, I., Dietz, S., Zopluoglu, C., Clarke, A., Lipsky, M., & Hartnett, C. (2020). Assessing a culture of mattering in a higher education context. Journal for the Study of Postsecondary and Tertiary Education, 5, 58-104. https://doi.org/10.28945/4539 <br>
[**Download/Request**](http://www.jspte.org/Volume5/JSPTEv5p085-104Prilleltensky6169.pdf)

- Zopluoglu, C. (2020). A Finite Mixture Item Response Theory Model for Continuous Measurement Outcomes. Educational and Psychological Measurement, 80(2), 346–364. https://doi.org/10.1177/0013164419856663 https://doi.org/10.1177/0013164419856663 <br>
[**Download/Request**](https://www.researchgate.net/publication/317095748)

- Zopluoglu, C. (2019). Computation of the Response Similarity Index M4 in R under the Dichotomous and Nominal Item Response Models. International Journal of Assessment Tools in Education , 6 (5) , 1-19 . DOI: 10.21449/ijate.527299 <br>
[**Download/Request**](https://dergipark.org.tr/en/pub/ijate/issue/43543/527299)

- Zopluoglu, C. (2019). Detecting Examinees With Item Preknowledge in Large-Scale Testing Using Extreme Gradient Boosting (XGBoost). Educational and Psychological Measurement, 79(5), 931–961. https://doi.org/10.1177/0013164419839439 <br>
[**Download/Request**](https://www.researchgate.net/publication/332158210) 

- Kohli, N., Peralta, Y., Zopluoglu, C., & Davison, M. L. (2018). A note on estimating single-class piecewise mixed-effects models with unknown change points. International Journal of Behavioral Development, 42(5), 518–524. https://doi.org/10.1177/0165025418759237 <br>
[**Download/Request**](https://www.researchgate.net/publication/322554638) 

- Sideridis, G.D., & Zopluoglu, C. (2018). Validation of response similarity analysis for the detection of academic cheating: An experimental study. Journal of Applied Measurement, 19(1), 59-75. <br>
[**Download/Request**](https://www.researchgate.net/publication/321342650)

- Sari, H.I., Huggins-Manley, A.C., & Zopluoglu, C. (2017). Comparing item selection methods in multidimensional computerized adaptive testing under different types of multidimensional structures. International Journal of Recent Scientific Research, 8 (8), 19269-19276. <br>
[**Download/Request**](http://recentscientific.com/sites/default/files/8247-A-2017.pdf)

- de l’Etoile,, Behura, S., & Zopluoglu, C. (2017). Acoustic parameters of infant-directed singing in mothers of infants with Down syndrome. Infant Behavior and Development, 49, 151-160. https://doi.org/10.1016/j.infbeh.2017.09.001 <br>
[**Download/Request**](https://www.researchgate.net/publication/334960784)

- Zopluoglu, C., & Davenport, E.C. (2017). A note on using eigenvalues in dimensionality assessment. Practical Assessment, Research & Evaluation, 22 (7), 1-10. <br>
[**Download/Request**](https://scholarworks.umass.edu/cgi/viewcontent.cgi?article=1358&context=pare)

- Brogaard, B,Marlow, K., Overgaard, M., Schwartz, B., Zopluoglu, C., Tomson, S., Neufeld, J., Sinke, C., Owen, C., Eagleman, D. (2017). Deaf hearing: Implicit discrimination of auditory content in a patient with mixed hearing loss. Philosophical Psychology, 30(1-2), 21-43. https://doi.org/10.1080/09515089.2016.1268680 <br>
[**Download/Request**](https://www.researchgate.net/publication/313483624)

- Myers, N. D., Ahn, S., Lu, M., Celimli, S., & Zopluoglu, C. (2017). Reordering and reflecting factors for simulation studies with exploratory factor analysis. Structural Equation Modeling: A Multidisciplinary Journal, 24(1), 112-128. https://doi.org/10.1080/10705511.2016.1230721 <br>
[**Download/Request**](https://www.researchgate.net/publication/308663171)

- Zopluoglu, C. (2016). Classification performance of answer-copying indices under different types of IRT models. Applied Psychological Measurement, 40(8), 592-607. https://doi.org/10.1177%2F0146621616664724 <br>
[**Download/Request**](https://www.researchgate.net/publication/307907874)

- Kohli, N., Harring J.R., & Zopluoglu, C. (2016). A finite mixture of nonlinear random coefficient models for continuous repeated measures data. Psychometrika, 81(3), 851-880. https://doi.org/10.1007/s11336-015-9462-0 <br>
[**Download/Request**](https://www.researchgate.net/publication/270958026)

- Zopluoglu, C. (2015). Evaluating the sampling performance of exploratory and cross-validated DETECT procedure with imperfect models. Multivariate Behavioral Research, 50(6), 632-644. https://doi.org/10.1080/00273171.2015.1070708 <br>
[**Download/Request**](https://www.researchgate.net/publication/281889397)

- Kohli, N., Hughes, J., Wang, C., Zopluoglu, C., & Davison, M. (2015). Fitting a linear-linear piecewise growth mixture model with unknown knots: A comparison of two common approaches to inference. Psychological Methods, 20(2), 259-275. http://dx.doi.org/10.1037/met0000034 <br>
[**Download/Request**](https://www.researchgate.net/publication/270286540)

- Kohli, N., Sullivan, A., Sadeh, S., & Zopluoglu, C. (2015). Longitudinal mathematics development of students with learning disabilities and students without disabilities: A comparison of linear, quadratic, and piecewise linear mixed effects models. Journal of School Psychology, 53(2),105-120. https://doi.org/10.1016/j.jsp.2014.12.002 <br>
[**Download/Request**](https://www.researchgate.net/publication/268149157)

- Zopluoglu, C., Harring J.R., & Kohli, N. (2014). FitPMM: An R routine to fit finite miture of piecewise mixed-effect models with unknown random knots. Applied Psychological Measurement, 38(7), 583-584. [Computer software]. https://doi.org/10.1177/0146621614540482 <br>
[**Download/Request**](https://www.researchgate.net/publication/262561927)

- Myers, N.D., Jin, Y., Ahn, S., Celimli, S., & Zopluoglu, C. (2015). Rotation to a partially specified target matrix in exploratory factor analysis in practice. Behavior Research Methods, 47(2), 494-505. https://doi.org/10.3758/s13428-014-0486-7 <br>
[**Download/Request**](https://www.researchgate.net/publication/262932403) <br>

- Van Norman E., Christ, T. J., Zopluoglu, C. (2013). The effects of baseline estimation on the reliability, validity, and precision of CBM-R growth estimates. School Psychology Quarterly, 28(3), 239-255. http://dx.doi.org/10.1037/spq0000023 <br>
[**Download/Request**](https://www.researchgate.net/publication/255787677)

- Christ, T. J., Monaghen, B., Zopluoglu, C. & Van Norman, E. R. (2013). Curriculum-Based measurement of oral reading: Evaluation of growth estimates derived with pre-post assessment methods. Assessment for Effective Intervention, 38(3), 139-153. https://doi.org/10.1016/j.jsp.2012.11.001 <br>
[**Download/Request**](https://www.researchgate.net/publication/235247019)


- Zopluoglu, C. (2013). A comparison of two estimation algorithms for Samejima’s continuous IRT model. Behavior Research Methods, 45(1), 54-64. https://doi.org/10.3758/s13428-012-0229-6 <br>
[**Download/Request**](https://www.researchgate.net/publication/228066472)

- Christ, T.J., Zopluoglu, C., Monaghen, B., & Van Norman, E.R. (2013). Curriculum- Based measurement of oral reading: Multi-study evaluation of schedule, duration and dataset quality on progress monitoring outcomes. Journal of School Psychology, 51(1), 19-57. https://doi.org/10.1016/j.jsp.2012.11.001 <br>
[**Download/Request**](https://www.researchgate.net/publication/235395434)

- Zopluoglu, C. (2013). CopyDetect: An R package to compute statistical indices for detecting answer copying on multiple-choice tests. Applied Psychological Measurement, 37(1), 75-77. [Computer software]. https://doi.org/10.1177/0146621612463119 <br>
[**Download/Request**](https://www.researchgate.net/publication/235247020)

- Zopluoglu, C. & Davenport, E.C. (2012). The empirical power and type-I error rates of the GBT and Omega indices in detecting answer copying on multiple-choice tests. Educational and Psychological Measurement, 72(6), 975-1000. https://doi.org/10.1177/0013164412442941 <br>
[**Download/Request**](https://www.researchgate.net/publication/235247021)

- Christ, T. J., Zopluoglu, C., Long, D. J., & Monaghen, B.D. (2012). Curriculum-Based measurement of oral reading (CBM-R): Quality of progress monitoring outcomes. Exceptional Children, 78(3), 356-373. https://doi.org/10.1177/001440291207800306 <br>
[**Download/Request**](https://www.researchgate.net/publication/235246998)

- Zopluoglu, C. (2012). EstCRM: An R package for Samejima's continuous IRT model. Applied Psychological Measurement, 36(2), 149-150. [Computer software]. https://doi.org/10.1177/0146621612436599 <br>
[**Download/Request**](https://www.researchgate.net/publication/235247025)

- Zopluoglu, C. (2012). A cross-national comparison of intra-class correlation coefficient in educational achievement outcomes. Journal of Measurement and Evaluation in Education and Psychology, 3(1), 242-278. <br>
[**Download/Request**](https://www.researchgate.net/publication/262297789)

# Book/Book Chapters

- Zopluoglu, C. (2017). Similarity, answer copying, and aberrance: Understanding the status quo. In G.J. Cizek & J.A. Wollack, Handbook of Detecting Cheating on Tests. Taylor & Francis. <br>
[**Download/Request**](https://www.researchgate.net/publication/309351878)


## Dead and Buried

- Zopluoglu, C. (buried). A Note on MLE estimation of person parameters for mixture IRT models.
[**Download/Request**](https://www.researchgate.net/publication/317095944)
